build:
  stage: build
  before_script: 
    - export VERSION=1.0.$CI_PIPELINE_IID
    - export IMAGE_NAME=$CI_REGISTRY_NAME
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$VERSION .
    - docker push $IMAGE_NAME:$VERSION