build:
  stage: build
  before_script: 
    - export VERSION=1.$CI_PIPELINE_IID
    - export IMAGE_NAME=$CI_REGISTRY_NAME
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$VERSION .
    - docker push $IMAGE_NAME:$VERSION