workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
- test
- build
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
